name: 'Hello World Action'
description: 'A simple GitHub Action that says Hello World'
author: 'Your Name'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'

outputs:
  greeting:
    description: 'The greeting message'

runs:
  using: 'node20'
  main: 'index.js'