name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci

      - name: Run Hello World Action
        id: hello
        uses: ./ # Use the action in the current repository
        with:
          who-to-greet: "GitHub"

      - name: Display the greeting
        run: echo "${{ steps.hello.outputs.greeting }}"
